
    language:c
      sudo:false #only for faster builds
       compiler:
        -gcc
      script:
        -gcc -o wiper_system wiper_system.c   //wecanusegccinsteadofclangtoo
        -./wiper_system
