matrix:
  include:
  -language:c
    sudo:false#onlyforfasterbuilds
      compiler:
        -clang
        -gcc
      script:
        -gcc -o test wiper_system.c   //wecanusegccinsteadofclangtoo
        -./wiper_system
